// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Api>>
abstract class Api implements RustOpaqueInterface {
  void backspace();

  String buffer();

  List<ApiCandidate> candidates({required BigInt limit});

  void clear();

  void clearUserWords();

  String exportUserWords();

  String inputKey({required String ch});

  String inputSpace();

  bool learnerEnabled();

  static Future<Api> load({required String path}) =>
      RustLib.instance.api.crateApiApiLoad(path: path);

  static Future<Api> loadFallback() =>
      RustLib.instance.api.crateApiApiLoadFallback();

  static Future<Api> loadFallbackSync() =>
      RustLib.instance.api.crateApiApiLoadFallbackSync();

  static Future<Api> loadSync({required String path}) =>
      RustLib.instance.api.crateApiApiLoadSync(path: path);

  ApiMode mode();

  void removeUserWord({required String text});

  List<ApiSymbolEntry> searchSymbols({required String keyword});

  String select({required BigInt index});

  void setLearner({required bool enabled});

  void setShift({required bool on_});

  void switchMode({required ApiMode mode});

  List<ApiBlock> symbolBlocks();

  List<ApiSymbolEntry> symbolsInBlock({required int id});
}

class ApiBlock {
  final int id;
  final int start;
  final int end;
  final String name;
  final bool common;

  const ApiBlock({
    required this.id,
    required this.start,
    required this.end,
    required this.name,
    required this.common,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      start.hashCode ^
      end.hashCode ^
      name.hashCode ^
      common.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiBlock &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          start == other.start &&
          end == other.end &&
          name == other.name &&
          common == other.common;
}

class ApiCandidate {
  final String text;
  final ApiCandidateKind kind;
  final BigInt score;

  const ApiCandidate({
    required this.text,
    required this.kind,
    required this.score,
  });

  @override
  int get hashCode => text.hashCode ^ kind.hashCode ^ score.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiCandidate &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          kind == other.kind &&
          score == other.score;
}

enum ApiCandidateKind { hanzi, english, emoji, symbol }

enum ApiMode { pinyin, english, number, symbol }

class ApiSymbolEntry {
  final String text;
  final String name;
  final List<String> keywords;
  final int block;
  final bool emoji;

  const ApiSymbolEntry({
    required this.text,
    required this.name,
    required this.keywords,
    required this.block,
    required this.emoji,
  });

  @override
  int get hashCode =>
      text.hashCode ^
      name.hashCode ^
      keywords.hashCode ^
      block.hashCode ^
      emoji.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiSymbolEntry &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          name == other.name &&
          keywords == other.keywords &&
          block == other.block &&
          emoji == other.emoji;
}
