// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 39284299;

  // MANUAL EDIT (re-apply after regen)
  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'opi_ffi',
        ioDirectory: '../../target/debug/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  void crateApiApiBackspace({required Api that});

  String crateApiApiBuffer({required Api that});

  List<ApiCandidate> crateApiApiCandidates({
    required Api that,
    required BigInt limit,
  });

  void crateApiApiClear({required Api that});

  void crateApiApiClearUserWords({required Api that});

  String crateApiApiExportUserWords({required Api that});

  String crateApiApiInputKey({required Api that, required String ch});

  String crateApiApiInputSpace({required Api that});

  bool crateApiApiLearnerEnabled({required Api that});

  Future<Api> crateApiApiLoad({required String path});

  Future<Api> crateApiApiLoadFallback();

  Future<Api> crateApiApiLoadFallbackSync();

  Future<Api> crateApiApiLoadSync({required String path});

  ApiMode crateApiApiMode({required Api that});

  void crateApiApiRemoveUserWord({required Api that, required String text});

  List<ApiSymbolEntry> crateApiApiSearchSymbols({
    required Api that,
    required String keyword,
  });

  String crateApiApiSelect({required Api that, required BigInt index});

  void crateApiApiSetLearner({required Api that, required bool enabled});

  void crateApiApiSetShift({required Api that, required bool on_});

  void crateApiApiSwitchMode({required Api that, required ApiMode mode});

  List<ApiBlock> crateApiApiSymbolBlocks({required Api that});

  List<ApiSymbolEntry> crateApiApiSymbolsInBlock({
    required Api that,
    required int id,
  });

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Api;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Api;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ApiPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  void crateApiApiBackspace({required Api that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiApiBackspaceConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiBackspaceConstMeta =>
      const TaskConstMeta(debugName: "Api_backspace", argNames: ["that"]);

  @override
  String crateApiApiBuffer({required Api that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiApiBufferConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiBufferConstMeta =>
      const TaskConstMeta(debugName: "Api_buffer", argNames: ["that"]);

  @override
  List<ApiCandidate> crateApiApiCandidates({
    required Api that,
    required BigInt limit,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
            that,
            serializer,
          );
          sse_encode_usize(limit, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_api_candidate,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiApiCandidatesConstMeta,
        argValues: [that, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiCandidatesConstMeta => const TaskConstMeta(
    debugName: "Api_candidates",
    argNames: ["that", "limit"],
  );

  @override
  void crateApiApiClear({required Api that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiApiClearConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiClearConstMeta =>
      const TaskConstMeta(debugName: "Api_clear", argNames: ["that"]);

  @override
  void crateApiApiClearUserWords({required Api that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiApiClearUserWordsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiClearUserWordsConstMeta => const TaskConstMeta(
    debugName: "Api_clear_user_words",
    argNames: ["that"],
  );

  @override
  String crateApiApiExportUserWords({required Api that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiApiExportUserWordsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiExportUserWordsConstMeta => const TaskConstMeta(
    debugName: "Api_export_user_words",
    argNames: ["that"],
  );

  @override
  String crateApiApiInputKey({required Api that, required String ch}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
            that,
            serializer,
          );
          sse_encode_String(ch, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiApiInputKeyConstMeta,
        argValues: [that, ch],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiInputKeyConstMeta =>
      const TaskConstMeta(debugName: "Api_input_key", argNames: ["that", "ch"]);

  @override
  String crateApiApiInputSpace({required Api that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiApiInputSpaceConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiInputSpaceConstMeta =>
      const TaskConstMeta(debugName: "Api_input_space", argNames: ["that"]);

  @override
  bool crateApiApiLearnerEnabled({required Api that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiApiLearnerEnabledConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiLearnerEnabledConstMeta =>
      const TaskConstMeta(debugName: "Api_learner_enabled", argNames: ["that"]);

  @override
  Future<Api> crateApiApiLoad({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiApiLoadConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiLoadConstMeta =>
      const TaskConstMeta(debugName: "Api_load", argNames: ["path"]);

  @override
  Future<Api> crateApiApiLoadFallback() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiApiLoadFallbackConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiLoadFallbackConstMeta =>
      const TaskConstMeta(debugName: "Api_load_fallback", argNames: []);

  @override
  Future<Api> crateApiApiLoadFallbackSync() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiApiLoadFallbackSyncConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiLoadFallbackSyncConstMeta =>
      const TaskConstMeta(debugName: "Api_load_fallback_sync", argNames: []);

  @override
  Future<Api> crateApiApiLoadSync({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiApiLoadSyncConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiLoadSyncConstMeta =>
      const TaskConstMeta(debugName: "Api_load_sync", argNames: ["path"]);

  @override
  ApiMode crateApiApiMode({required Api that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_mode,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiApiModeConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiModeConstMeta =>
      const TaskConstMeta(debugName: "Api_mode", argNames: ["that"]);

  @override
  void crateApiApiRemoveUserWord({required Api that, required String text}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
            that,
            serializer,
          );
          sse_encode_String(text, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiApiRemoveUserWordConstMeta,
        argValues: [that, text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiRemoveUserWordConstMeta => const TaskConstMeta(
    debugName: "Api_remove_user_word",
    argNames: ["that", "text"],
  );

  @override
  List<ApiSymbolEntry> crateApiApiSearchSymbols({
    required Api that,
    required String keyword,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
            that,
            serializer,
          );
          sse_encode_String(keyword, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_api_symbol_entry,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiApiSearchSymbolsConstMeta,
        argValues: [that, keyword],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiSearchSymbolsConstMeta => const TaskConstMeta(
    debugName: "Api_search_symbols",
    argNames: ["that", "keyword"],
  );

  @override
  String crateApiApiSelect({required Api that, required BigInt index}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
            that,
            serializer,
          );
          sse_encode_usize(index, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiApiSelectConstMeta,
        argValues: [that, index],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiSelectConstMeta =>
      const TaskConstMeta(debugName: "Api_select", argNames: ["that", "index"]);

  @override
  void crateApiApiSetLearner({required Api that, required bool enabled}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
            that,
            serializer,
          );
          sse_encode_bool(enabled, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiApiSetLearnerConstMeta,
        argValues: [that, enabled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiSetLearnerConstMeta => const TaskConstMeta(
    debugName: "Api_set_learner",
    argNames: ["that", "enabled"],
  );

  @override
  void crateApiApiSetShift({required Api that, required bool on_}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
            that,
            serializer,
          );
          sse_encode_bool(on_, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiApiSetShiftConstMeta,
        argValues: [that, on_],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiSetShiftConstMeta => const TaskConstMeta(
    debugName: "Api_set_shift",
    argNames: ["that", "on_"],
  );

  @override
  void crateApiApiSwitchMode({required Api that, required ApiMode mode}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
            that,
            serializer,
          );
          sse_encode_api_mode(mode, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiApiSwitchModeConstMeta,
        argValues: [that, mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiSwitchModeConstMeta => const TaskConstMeta(
    debugName: "Api_switch_mode",
    argNames: ["that", "mode"],
  );

  @override
  List<ApiBlock> crateApiApiSymbolBlocks({required Api that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_api_block,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiApiSymbolBlocksConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiSymbolBlocksConstMeta =>
      const TaskConstMeta(debugName: "Api_symbol_blocks", argNames: ["that"]);

  @override
  List<ApiSymbolEntry> crateApiApiSymbolsInBlock({
    required Api that,
    required int id,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
            that,
            serializer,
          );
          sse_encode_u_16(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_api_symbol_entry,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiApiSymbolsInBlockConstMeta,
        argValues: [that, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApiSymbolsInBlockConstMeta => const TaskConstMeta(
    debugName: "Api_symbols_in_block",
    argNames: ["that", "id"],
  );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Api => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Api => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi;

  @protected
  Api
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ApiImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Api
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ApiImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Api
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ApiImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Api
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ApiImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  ApiBlock dco_decode_api_block(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ApiBlock(
      id: dco_decode_u_16(arr[0]),
      start: dco_decode_u_32(arr[1]),
      end: dco_decode_u_32(arr[2]),
      name: dco_decode_String(arr[3]),
      common: dco_decode_bool(arr[4]),
    );
  }

  @protected
  ApiCandidate dco_decode_api_candidate(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ApiCandidate(
      text: dco_decode_String(arr[0]),
      kind: dco_decode_api_candidate_kind(arr[1]),
      score: dco_decode_u_64(arr[2]),
    );
  }

  @protected
  ApiCandidateKind dco_decode_api_candidate_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ApiCandidateKind.values[raw as int];
  }

  @protected
  ApiMode dco_decode_api_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ApiMode.values[raw as int];
  }

  @protected
  ApiSymbolEntry dco_decode_api_symbol_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ApiSymbolEntry(
      text: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      keywords: dco_decode_list_String(arr[2]),
      block: dco_decode_u_16(arr[3]),
      emoji: dco_decode_bool(arr[4]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ApiBlock> dco_decode_list_api_block(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_api_block).toList();
  }

  @protected
  List<ApiCandidate> dco_decode_list_api_candidate(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_api_candidate).toList();
  }

  @protected
  List<ApiSymbolEntry> dco_decode_list_api_symbol_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_api_symbol_entry).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  Api
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ApiImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Api
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ApiImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Api
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ApiImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Api
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ApiImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  ApiBlock sse_decode_api_block(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_16(deserializer);
    var var_start = sse_decode_u_32(deserializer);
    var var_end = sse_decode_u_32(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_common = sse_decode_bool(deserializer);
    return ApiBlock(
      id: var_id,
      start: var_start,
      end: var_end,
      name: var_name,
      common: var_common,
    );
  }

  @protected
  ApiCandidate sse_decode_api_candidate(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_text = sse_decode_String(deserializer);
    var var_kind = sse_decode_api_candidate_kind(deserializer);
    var var_score = sse_decode_u_64(deserializer);
    return ApiCandidate(text: var_text, kind: var_kind, score: var_score);
  }

  @protected
  ApiCandidateKind sse_decode_api_candidate_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ApiCandidateKind.values[inner];
  }

  @protected
  ApiMode sse_decode_api_mode(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ApiMode.values[inner];
  }

  @protected
  ApiSymbolEntry sse_decode_api_symbol_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_text = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_keywords = sse_decode_list_String(deserializer);
    var var_block = sse_decode_u_16(deserializer);
    var var_emoji = sse_decode_bool(deserializer);
    return ApiSymbolEntry(
      text: var_text,
      name: var_name,
      keywords: var_keywords,
      block: var_block,
      emoji: var_emoji,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ApiBlock> sse_decode_list_api_block(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ApiBlock>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_api_block(deserializer));
    }
    return ans_;
  }

  @protected
  List<ApiCandidate> sse_decode_list_api_candidate(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ApiCandidate>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_api_candidate(deserializer));
    }
    return ans_;
  }

  @protected
  List<ApiSymbolEntry> sse_decode_list_api_symbol_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ApiSymbolEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_api_symbol_entry(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
    Api self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ApiImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
    Api self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ApiImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
    Api self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ApiImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApi(
    Api self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ApiImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_api_block(ApiBlock self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.id, serializer);
    sse_encode_u_32(self.start, serializer);
    sse_encode_u_32(self.end, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_bool(self.common, serializer);
  }

  @protected
  void sse_encode_api_candidate(ApiCandidate self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.text, serializer);
    sse_encode_api_candidate_kind(self.kind, serializer);
    sse_encode_u_64(self.score, serializer);
  }

  @protected
  void sse_encode_api_candidate_kind(
    ApiCandidateKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_api_mode(ApiMode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_api_symbol_entry(
    ApiSymbolEntry self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.text, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_list_String(self.keywords, serializer);
    sse_encode_u_16(self.block, serializer);
    sse_encode_bool(self.emoji, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_api_block(
    List<ApiBlock> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_api_block(item, serializer);
    }
  }

  @protected
  void sse_encode_list_api_candidate(
    List<ApiCandidate> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_api_candidate(item, serializer);
    }
  }

  @protected
  void sse_encode_list_api_symbol_entry(
    List<ApiSymbolEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_api_symbol_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class ApiImpl extends RustOpaque implements Api {
  // Not to be used by end users
  ApiImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ApiImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_Api,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_Api,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_ApiPtr,
  );

  void backspace() => RustLib.instance.api.crateApiApiBackspace(that: this);

  String buffer() => RustLib.instance.api.crateApiApiBuffer(that: this);

  List<ApiCandidate> candidates({required BigInt limit}) =>
      RustLib.instance.api.crateApiApiCandidates(that: this, limit: limit);

  void clear() => RustLib.instance.api.crateApiApiClear(that: this);

  void clearUserWords() =>
      RustLib.instance.api.crateApiApiClearUserWords(that: this);

  String exportUserWords() =>
      RustLib.instance.api.crateApiApiExportUserWords(that: this);

  String inputKey({required String ch}) =>
      RustLib.instance.api.crateApiApiInputKey(that: this, ch: ch);

  String inputSpace() => RustLib.instance.api.crateApiApiInputSpace(that: this);

  bool learnerEnabled() =>
      RustLib.instance.api.crateApiApiLearnerEnabled(that: this);

  ApiMode mode() => RustLib.instance.api.crateApiApiMode(that: this);

  void removeUserWord({required String text}) =>
      RustLib.instance.api.crateApiApiRemoveUserWord(that: this, text: text);

  List<ApiSymbolEntry> searchSymbols({required String keyword}) => RustLib
      .instance
      .api
      .crateApiApiSearchSymbols(that: this, keyword: keyword);

  String select({required BigInt index}) =>
      RustLib.instance.api.crateApiApiSelect(that: this, index: index);

  void setLearner({required bool enabled}) =>
      RustLib.instance.api.crateApiApiSetLearner(that: this, enabled: enabled);

  void setShift({required bool on_}) =>
      RustLib.instance.api.crateApiApiSetShift(that: this, on_: on_);

  void switchMode({required ApiMode mode}) =>
      RustLib.instance.api.crateApiApiSwitchMode(that: this, mode: mode);

  List<ApiBlock> symbolBlocks() =>
      RustLib.instance.api.crateApiApiSymbolBlocks(that: this);

  List<ApiSymbolEntry> symbolsInBlock({required int id}) =>
      RustLib.instance.api.crateApiApiSymbolsInBlock(that: this, id: id);
}
